module.exports = {
  GAME_INTRO:"GAME_INTRO",
  FETCH_INTRO:"FETCH_INTRO",
  HOST_JOINED:"HOST_JOINED",
  HOST_STARTED_GAME:"HOST_STARTED_GAME",
  SHOW_PIN:"SHOW_PIN",
  UPDATE_PLAYERS_IN_LOBBY:"UPDATE_PLAYERS_IN_LOBBY",
  PLAYER_JOINED:"PLAYER_JOINED",
  PLAYER_JOINED_SUCCESSFULLY:"PLAYER_JOINED_SUCCESSFULLY",
  GAME_NOT_FOUND:"GAME_NOT_FOUND",
  GAME_HAS_STARTED:"GAME_HAS_STARTED",
  READY:"READY",
  FETCH_QUESTION:"FETCH_QUESTION",
  RECEIVE_QUESTION:"RECEIVE_QUESTION",
  RECEIVE_ANSWER_OPTIONS:"RECEIVE_ANSWER_OPTIONS",
  ANSWER_SUBMITTED:"ANSWER_SUBMITTED"
}
