module.exports = {
  GAME_INTRO:"GAME_INTRO",
  FETCH_INTRO:"FETCH_INTRO",
  HOST_JOINED:"HOST_JOINED",
  HOST_STARTED_GAME:"GAME_STARTED",
  SHOW_PIN:"SHOW_PIN",
  UPDATE_PLAYERS_IN_LOBBY:"UPDATE_PLAYERS_IN_LOBBY",
  PLAYER_JOINED:"PLAYER_JOINED",
  GAME_NOT_FOUND:"GAME_NOT_FOUND"
}
